import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, RefreshCw, ShieldCheck } from "lucide-react";
import { useLocation } from "wouter";
import MerchantWorkspaceShell from "@/components/MerchantWorkspaceShell";

const inactivePlaceholders = [
  { name: "Local model runtime", state: "Inactive placeholder", requirement: "Verified interpreter, model artifact location, and resource budget", behavior: "No model runtime is enabled from this placeholder." },
  { name: "Published Razorpay webhook delivery", state: "Awaiting live proof", requirement: "Published endpoint plus separately configured signed webhook", behavior: "The app accepts verified events only; no delivery is claimed here." },
  { name: "Carrier fulfilment integration", state: "Inactive placeholder", requirement: "Verified carrier provider, event schema, and merchant authorization", behavior: "Fulfilment remains a source-labelled merchant record." },
  { name: "Razorpay refund execution", state: "Merchant-gated", requirement: "Captured payment, prepared local request, explicit merchant approval, and signed outcome", behavior: "No refund is initiated or confirmed from settings." },
  { name: "External dispute response", state: "Merchant-gated", requirement: "Signed external dispute, complete evidence, and explicit merchant decision", behavior: "No contest or acceptance is submitted automatically." },
];

export default function SettingsWorkspace() {
  const [, setLocation] = useLocation();
  const connection = trpc.razorpayConnection.useQuery(undefined, { retry: 1 });
  return <MerchantWorkspaceShell><main className="min-h-screen bg-slate-50 p-4 text-slate-950 md:p-8"><section className="mx-auto max-w-4xl space-y-6"><div className="rounded-xl border bg-white p-6"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-sky-700">Merchant account</p><h1 className="mt-1 text-3xl font-semibold">Account & settings</h1><p className="mt-2 text-sm text-slate-600">Read-only connection readiness. Secrets and unverified values are never shown in the browser.</p></div><Button variant="outline" onClick={() => setLocation("/")}><ArrowLeft className="mr-2 h-4 w-4" />Merchant home</Button></div><div className="mt-6 rounded-lg border p-5"><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-sky-700" /><b>Razorpay connection</b></div>{connection.isLoading ? <p className="mt-3 text-sm text-slate-600">Checking server-side account access…</p> : connection.isError ? <p className="mt-3 text-sm text-red-700">Connection check failed: {connection.error.message}</p> : <pre className="mt-4 overflow-auto rounded bg-slate-950 p-4 text-xs text-emerald-200">{JSON.stringify(connection.data, null, 2)}</pre>}<Button className="mt-4" variant="outline" onClick={() => connection.refetch()}><RefreshCw className="mr-2 h-4 w-4" />Refresh connection</Button></div></div><section className="rounded-xl border bg-white p-6"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-sky-700">Inactive configuration registry</p><h2 className="mt-1 text-xl font-semibold">Unverified capabilities stay placeholders</h2><p className="mt-2 text-sm text-slate-600">No values are guessed, no secrets are displayed, and these entries have no runtime effect until their activation requirements are independently verified.</p></div><div className="mt-5 space-y-3">{inactivePlaceholders.map(item => <article key={item.name} className="rounded-lg border border-dashed p-4"><div className="flex flex-wrap items-center justify-between gap-2"><b>{item.name}</b><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-semibold text-slate-700">{item.state}</span></div><p className="mt-2 text-sm text-slate-700"><b>Activation requirement:</b> {item.requirement}</p><p className="mt-1 text-sm text-slate-600"><b>Safe current behavior:</b> {item.behavior}</p></article>)}</div></section></section></main></MerchantWorkspaceShell>;
}
