export function CapabilityStatusPanel() {
  const rows = [
    ["Local case and evidence workflow", "Implemented locally", "Merchant-controlled case, document, evidence, and audit workflow."],
    ["Razorpay account read", "Test-mode verified", "Read-only account access is verified; it does not prove a webhook delivery."],
    ["Webhook verification and burst guard", "Implemented and regression-tested", "HMAC, idempotency, a 1 MB raw-payload guard, a 120-request-per-source-IP-per-minute process-local guard, and source-safe parser errors are tested; no live delivery is implied."],
    ["Risk Operations expansion", "Implemented and regression-tested", "Candidate evidence mapping, protected search, manual owner/level/note state, safe triage, trends, usage counts, and source-boundary screens remain non-automating."],
    ["Internal teams and audit export", "Implemented locally", "Viewer/reviewer/approver checks govern local workspace actions; an approver can release only a redacted local audit download. No invitation email, provider role, or provider write is created."],
    ["Payments, refunds, external disputes", "Awaiting live proof", "Only source-recorded events can establish these external states."],
    ["Carrier integration", "Inactive placeholder", "Requires carrier contract, authentication, and event provenance before activation."],
  ] as const;
  return <section className="rounded-xl border border-slate-200 bg-white p-5"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-sky-800">Reality check</p><h2 className="mt-1 text-xl font-semibold text-slate-950">Real versus simulated capability status</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[38rem] text-left text-sm"><thead className="border-b text-xs uppercase tracking-wide text-slate-500"><tr><th className="pb-2 pr-4">Feature</th><th className="pb-2 pr-4">Status</th><th className="pb-2">Boundary</th></tr></thead><tbody>{rows.map(([feature, status, boundary]) => <tr key={feature} className="border-b border-slate-100 align-top"><td className="py-3 pr-4 font-medium text-slate-900">{feature}</td><td className="py-3 pr-4"><span className="rounded bg-slate-100 px-2 py-1 text-xs font-semibold text-slate-700">{status}</span></td><td className="py-3 text-slate-600">{boundary}</td></tr>)}</tbody></table></div><p className="mt-4 rounded-lg bg-slate-50 p-3 text-xs leading-5 text-slate-600"><b>Current local validation snapshot:</b> 47 test files and 128 tests passed, alongside TypeScript, production build, and responsive non-mutating entry-state checks. This is an implementation checkpoint, not a CI badge, service-level commitment, or production-uptime claim.</p></section>;
}
