import { customerSpaceHref, dashboardNavigation, disputeOperationNavigation } from "@/lib/navigation";
import { Menu, Settings, ShieldCheck, X } from "lucide-react";
import { ReactNode, useState } from "react";
import { useLocation } from "wouter";

function isActiveRoute(pathname: string, href: string) {
  return href === "/" ? pathname === "/" : pathname === href;
}

export default function MerchantWorkspaceShell({ children }: { children: ReactNode }) {
  const [location] = useLocation();
  const [mobileOpen, setMobileOpen] = useState(false);
  const close = () => setMobileOpen(false);
  const itemClass = (href: string) => `flex items-center gap-3 rounded-lg px-3 py-2 text-sm transition-colors ${isActiveRoute(location, href) ? "bg-sky-100 font-semibold text-sky-950" : "text-slate-600 hover:bg-slate-100 hover:text-slate-950"}`;

  const navigation = <nav className="space-y-5" aria-label="DisputeShield workspaces"><div><p className="px-3 text-[10px] font-bold uppercase tracking-[0.16em] text-slate-400">Workspace</p><div className="mt-2 space-y-1">{dashboardNavigation.map(item => { const Icon = item.icon; return <a key={item.label} className={itemClass(item.href)} href={item.href} onClick={close}><Icon className="h-4 w-4" />{item.label}</a>; })}</div></div><div><p className="px-3 text-[10px] font-bold uppercase tracking-[0.16em] text-slate-400">Dispute operations</p><div className="mt-2 space-y-1">{disputeOperationNavigation.map(item => { const Icon = item.icon; return <a key={item.label} className={itemClass(item.href)} href={item.href} onClick={close}><Icon className="h-4 w-4" />{item.label}{item.label === "Evidence packets" && <span className="ml-auto rounded bg-emerald-100 px-1.5 py-0.5 text-[10px] font-bold text-emerald-800">NEW</span>}</a>; })}</div></div><div><p className="px-3 text-[10px] font-bold uppercase tracking-[0.16em] text-slate-400">Buyer workspace</p><a className={itemClass(customerSpaceHref)} href={customerSpaceHref} onClick={close}><ShieldCheck className="h-4 w-4" />Customer Space</a></div></nav>;

  return <div className="min-h-screen bg-slate-50 text-slate-950"><aside className="fixed inset-y-0 left-0 z-40 hidden w-64 overflow-y-auto border-r border-slate-200 bg-white px-4 py-5 lg:block"><a href="/" className="mb-8 flex items-center gap-2 px-2 text-lg font-semibold tracking-tight text-slate-950"><span className="text-sky-600">◢</span>DisputeShield</a>{navigation}<div className="mt-8 border-t border-slate-200 pt-4"><a className={itemClass("/settings")} href="/settings"><Settings className="h-4 w-4" />Account & settings</a><p className="mt-4 px-3 text-[10px] font-semibold uppercase tracking-wide text-emerald-700">● Razorpay connected</p></div></aside><header className="sticky top-0 z-30 flex items-center justify-between border-b border-slate-200 bg-white px-4 py-3 lg:hidden"><a href="/" className="font-semibold text-slate-950"><span className="text-sky-600">◢</span> DisputeShield</a><button className="rounded-md border border-slate-300 p-2" aria-label="Open workspace navigation" onClick={() => setMobileOpen(true)}><Menu className="h-5 w-5" /></button></header>{mobileOpen && <div className="fixed inset-0 z-50 lg:hidden"><button className="absolute inset-0 bg-slate-950/30" aria-label="Close workspace navigation" onClick={close} /><aside className="relative h-full w-72 overflow-y-auto bg-white px-4 py-5 shadow-2xl"><div className="mb-7 flex items-center justify-between"><a href="/" className="text-lg font-semibold" onClick={close}><span className="text-sky-600">◢</span> DisputeShield</a><button className="rounded-md border border-slate-300 p-2" aria-label="Close workspace navigation" onClick={close}><X className="h-5 w-5" /></button></div>{navigation}<div className="mt-8 border-t border-slate-200 pt-4"><a className={itemClass("/settings")} href="/settings" onClick={close}><Settings className="h-4 w-4" />Account & settings</a></div></aside></div>}<div className="lg:ml-64">{children}</div></div>;
}
