import { AlertTriangle, Clock3, GitBranch, ShieldAlert, Sparkles } from "lucide-react";

export function ProactiveRiskPanel({ data, mode }: { data: any; mode: "reports" | "graph" | "learning" }) {
  if (!data) return <section className="rounded-xl border bg-white p-5 text-sm text-slate-600">Loading proactive risk intelligence…</section>;
  if (mode === "graph") return <section className="rounded-xl border bg-white p-5"><div className="flex items-start gap-3"><GitBranch className="mt-0.5 h-5 w-5 text-sky-700" /><div><h2 className="font-semibold">Evidence Integrity Graph</h2><p className="mt-1 text-sm text-slate-600">Links only source-labelled order, payment, fulfilment, evidence, and local-resolution facts. A missing node is an evidence gap, not a negative customer finding.</p></div></div>{data.graph?.length ? <div className="mt-4 space-y-4">{data.graph.map((item: any) => <article key={item.caseReference} className="rounded-lg border p-4"><b className="text-sm">{item.caseReference}</b><div className="mt-3 flex flex-wrap items-center gap-2">{item.nodes.map((node: any, index: number) => <span key={node.id} className="flex items-center gap-2"><span className={`rounded-full border px-2 py-1 text-xs ${node.state === "verified" ? "border-emerald-200 bg-emerald-50 text-emerald-800" : node.state === "missing" ? "border-amber-200 bg-amber-50 text-amber-900" : "border-slate-200 bg-slate-50 text-slate-700"}`}>{node.label} · {node.state}</span>{index < item.nodes.length - 1 && <span className="text-slate-400">→</span>}</span>)}</div><p className="mt-2 text-xs text-slate-500">Sources: {item.nodes.map((node: any) => node.source).join(" · ")}</p></article>)}</div> : <Empty text="No merchant-scoped customer cases have created an evidence graph yet." />}</section>;
  if (mode === "learning") return <section className="rounded-xl border bg-white p-5"><div className="flex items-start gap-3"><Sparkles className="mt-0.5 h-5 w-5 text-sky-700" /><div><h2 className="font-semibold">Outcome Learning Loop</h2><p className="mt-1 text-sm text-slate-600">The system reports only recorded outcomes. It does not guarantee a win or change contest/refund decisions automatically.</p></div></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><Stat label="Resolved local cases" value={data.outcomeLearning?.observedLocalResolutions ?? 0} /><Stat label="Withdrawn local cases" value={data.outcomeLearning?.withdrawnLocalCases ?? 0} /><Stat label="Confirmed external outcomes" value={data.outcomeLearning?.externalOutcomeRecords ?? 0} /></div><p className="mt-4 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-950">{data.outcomeLearning?.boundary}</p></section>;
  return <section className="space-y-5"><section className="rounded-xl border bg-white p-5"><div className="flex items-start gap-3"><AlertTriangle className="mt-0.5 h-5 w-5 text-amber-700" /><div><h2 className="font-semibold">Fulfilment Risk Sentinel & Evidence Freshness</h2><p className="mt-1 text-sm text-slate-600">Operational signals are based on merchant fulfilment records and protected customer-case metadata—not customer profiling.</p></div></div>{data.signals?.length ? <div className="mt-4 grid gap-3 lg:grid-cols-2">{data.signals.map((signal: any) => <article key={signal.key} className="rounded-lg border p-4"><div className="flex items-center justify-between gap-3"><b>{signal.title}</b><span className={`rounded-full px-2 py-1 text-xs font-semibold ${signal.level === "elevated" ? "bg-red-100 text-red-800" : signal.level === "review" ? "bg-amber-100 text-amber-900" : "bg-sky-100 text-sky-800"}`}>{signal.level}</span></div><p className="mt-2 text-sm text-slate-700">{signal.why}</p><p className="mt-2 text-sm font-medium text-slate-900">Next: {signal.nextAction}</p><small className="mt-2 block text-slate-500">{signal.caseReference} · {signal.source}</small></article>)}</div> : <Empty text="No active fulfilment or evidence-freshness risk is currently detected from the available local records." />}</section><section className="rounded-xl border bg-white p-5"><div className="flex items-start gap-3"><Clock3 className="mt-0.5 h-5 w-5 text-sky-700" /><div><h2 className="font-semibold">Merchant SLA Recovery Board</h2><p className="mt-1 text-sm text-slate-600">Prioritises factual review work; it does not send messages, approve refunds, or escalate to a bank.</p></div></div>{data.slaBoard?.length ? <div className="mt-4 space-y-2">{data.slaBoard.map((item: any) => <article key={item.caseReference} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border p-3"><div><b>{item.caseReference}</b><p className="mt-1 text-sm text-slate-600">{item.nextAction}</p></div><span className="text-sm text-slate-500">{item.ageHours}h · owner: {item.owner} · {item.level}</span></article>)}</div> : <Empty text="No active local customer case requires SLA recovery work." />}</section></section>;
}

function Stat({ label, value }: { label: string; value: number }) { return <article className="rounded-lg border p-3"><span className="text-xs uppercase tracking-wide text-slate-500">{label}</span><b className="mt-1 block text-xl">{value}</b></article>; }
function Empty({ text }: { text: string }) { return <div className="mt-4 rounded-lg border border-dashed p-5 text-sm text-slate-600"><ShieldAlert className="mb-2 h-5 w-5" />{text}</div>; }
