import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Bot, FileCheck2, ShieldAlert, Sparkles } from "lucide-react";

export function RiskNarrativeCard({ caseReference }: { caseReference: string }) {
  const narrative = trpc.generateCaseRiskNarrative.useMutation();
  const data = narrative.data;
  return <section className="mt-5 rounded-xl border border-sky-200 bg-sky-50/60 p-5">
    <div className="flex flex-wrap items-start justify-between gap-4">
      <div><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.14em] text-sky-800"><Sparkles className="h-4 w-4" /> AI risk narrative</div><h3 className="mt-2 text-lg font-semibold text-slate-950">Fact-cited advisory, never an automated decision</h3><p className="mt-1 max-w-2xl text-sm text-slate-600">Creates a short merchant briefing from this protected case’s source-labelled payment, fulfilment, document, return, and refund facts. It cannot change a recommendation or trigger an action.</p></div>
      <Button onClick={() => narrative.mutate({ caseReference })} disabled={narrative.isPending} className="bg-sky-700 hover:bg-sky-800"><Bot className="mr-2 h-4 w-4" />{narrative.isPending ? "Checking cited facts…" : data ? "Refresh advisory" : "Create advisory"}</Button>
    </div>
    {narrative.isError && <div className="mt-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-800">The advisory could not be created: {narrative.error.message}</div>}
    {data && <div className="mt-4 grid gap-4 lg:grid-cols-[1fr_16rem]"><article className="rounded-lg border border-sky-100 bg-white p-4"><div className="flex items-center gap-2"><FileCheck2 className="h-4 w-4 text-sky-700" /><b className="text-sm text-slate-900">{data.mode === "ai_assisted" ? "AI-generated summary" : "Deterministic safe fallback"}</b></div><div className="mt-3 rounded-lg bg-slate-50 p-3"><div className="flex items-center justify-between gap-3"><span className="text-xs font-semibold uppercase tracking-wide text-slate-600">Evidence readiness</span><b className="text-sm text-slate-900">{data.readinessScore}%</b></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full rounded-full bg-sky-600" style={{ width: `${data.readinessScore}%` }} /></div><p className="mt-2 text-xs leading-5 text-slate-600">Present: {data.evidencePresent.join(", ") || "none"}. Missing: {data.evidenceMissing.join(", ") || "none"}.</p></div><p className="mt-3 text-sm leading-6 text-slate-700">{data.summary}</p><div className="mt-3 border-t border-slate-100 pt-3"><span className="text-xs font-semibold uppercase tracking-wide text-slate-500">Recommended operational step</span><p className="mt-1 text-sm font-medium text-slate-900">{data.recommendation}</p></div></article><aside className="rounded-lg border border-sky-100 bg-white p-4"><span className="text-xs font-semibold uppercase tracking-wide text-slate-500">Cited records</span><div className="mt-2 space-y-2">{data.citations.map(source => <span key={source} className="block rounded bg-slate-100 px-2 py-1 text-xs text-slate-700">{source}</span>)}</div><p className="mt-4 text-[11px] leading-4 text-slate-500">Fact-sheet hash: {data.factSheetHash.slice(0, 12)}…</p><p className="mt-1 text-[11px] leading-4 text-slate-500">Prompt version: {data.promptVersion}</p></aside></div>}
    {data && <div className="mt-4 flex gap-2 rounded-lg border border-amber-200 bg-amber-50 p-3 text-xs leading-5 text-amber-950"><ShieldAlert className="mt-0.5 h-4 w-4 shrink-0" /><span>{data.boundary}{data.reason ? ` ${data.reason}` : ""}</span></div>}
  </section>;
}
